Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;


namespace personalblog.Models
{
    public enum PostStatus
    {
        Draft = 0,
        Published = 1,
        Unpublished = 2
    }
    public class Post
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Subtitle { get; set; }
        [Required]
        public string Body { get; set; }
        public DateTime CreatedAt { get; set; }

        [Display(Name = "Category")]
        public int Categoryid { get; set; }
        public byte Status { get; set; }
        public virtual Category Category { get; set; }

        public virtual ICollection<Comment> Comment { get; set; }

        [Required]
        [StringLength(450)]
        public string AuthorId { get; set; }
        public virtual IdentityUser Author { get; set; }
    }
}

Areas/Author/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using personalblog.DataContext;
using System.Security.Claims;
using personalblog.Models;
using personalblog.Models.ViewModels;

namespace personalblog.Areas.Author.Controllers
{
    [Area("Author")]
    [Authorize]
    public class PostsController : Controller
    {
        private readonly BlogContext _context;

        public PostsController(BlogContext _context)
        {
            this._context = _context;
        }

        private async Task<SelectList> GenerateList()
        {
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return new SelectList(await _context.Categories
                                    .Where(c => c.AuthorId == userid)
                                    .OrderBy(c => c.Categoryname).ToListAsync(), "Cateid", "Categoryname");

        }
        private void PopulateViewData(string userid)
        {
            ViewData["PostCount"] = _context.Posts
                      .Where(p => p.AuthorId == userid)
                      .Count();
            ViewData["categoryCount"] = _context.Categories
            .Where(c => c.AuthorId == userid)
            .Count();
            ViewData["commentCount"] = _context.Comments
           .Include(e => e.Posts)
           .Where(e => e.Posts.AuthorId == userid)
           .Count();
        }


        // GET: Posts

        public async Task<IActionResult> Index()
        {
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            PopulateViewData(userid);
            return View(await _context.Posts
            .Include(p => p.Category)
            .Where(p => p.AuthorId == userid)
            .ToListAsync());
        }
        [HttpPost]
        public IActionResult Publish(Guid Id)
        {
            var post = _context.Posts.Find(Id);
            if (post == null)
            {
                return RedirectToAction(nameof(Index));
            }
            post.Status = (byte)PostStatus.Published;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
        [HttpPost]
        public IActionResult Unpublish(Guid Id)
        {
            var post = _context.Posts.Find(Id);
            if (post == null)
            {
                return RedirectToAction(nameof(Index));
            }
            post.Status = (byte)PostStatus.Unpublished;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }


        // GET: Posts/Details/5


        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
            .Include(p => p.Author)
            .Include(p => p.Comment)
             .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(new PostCommentVM()
            {
                Post = post,
                PostId = post.Id,

            });
        }
        [HttpPost]
        [ActionName("details")]
        [Area("Author")]
        public async Task<IActionResult> CreateComment(PostCommentVM model)
        {
            if (ModelState.IsValid)
            {
                var comment = new Comment()
                {
                    Postid = model.PostId,
                    CommentText = model.CommentText,
                    Name = "Testing",
                    CommentDate = DateTime.UtcNow
                };
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), nameof(Details), comment.Postid);
                // return CreatedAtRoute("Author", comment);

            }
            return View(nameof(Index));

        }



        // GET: Posts/Create

        public async Task<IActionResult> Create()
        {
            ViewBag.Categoryid = await GenerateList();
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // [Route("{action=Index", Name = "Author")]
        [Area("Author")]
        public async Task<IActionResult> Create([Bind("Id,Title,Categoryid,Subtitle,Body")] PostVM post)
        {
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                var data = new Post()
                {
                    Id = Guid.NewGuid(),
                    Title = post.Title,
                    Categoryid = post.Categoryid,
                    Subtitle = post.Subtitle,
                    Body = post.Body,
                    AuthorId = userid,
                    CreatedAt = DateTime.UtcNow
                };
                _context.Add(data);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categoryid = GenerateList();
            return View(post);
        }

        // GET: Posts/Edit/5

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var post = await _context.Posts.SingleOrDefaultAsync(p => p.Id == id && p.AuthorId == userid);
            if (post == null)
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categoryid = await GenerateList();

            return View(new PostVM() { Id = post.Id, Title = post.Title, Categoryid = post.Categoryid, Subtitle = post.Subtitle, Body = post.Body });
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //XSS
        [ValidateAntiForgeryToken]
        [Area("Author")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Title,Subtitle,Body,Categoryid")] PostVM post)
        {
            if (ModelState.IsValid)
            {
                var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var data = await _context.Posts.SingleOrDefaultAsync(p => p.Id == id && p.AuthorId == userid);
                data.Title = post.Title;
                data.Subtitle = post.Subtitle;
                data.Body = post.Body;
                data.Categoryid = post.Categoryid;
                // _context.Update(post);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categoryid = GenerateList();
            return View(post);

            // if (id != post.Id)
            // {
            //     return NotFound();
            // }


            // if (ModelState.IsValid)
            // {
            //     var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            //     var data = await _context.Posts.SingleOrDefaultAsync(p => p.Id == id && p.AuthorId == userid);
            //     if (data == null)
            //     {
            //         return NotFound();
            //     }

            //     try
            //     {
            //         data.Title = post.Title;
            //         data.Subtitle = post.Subtitle;
            //         data.Body = post.Body;
            //         data.Categoryid = post.Categoryid;
            //         // _context.Update(post);

            //         await _context.SaveChangesAsync();
            //     }
            //     catch (DbUpdateConcurrencyException)
            //     {
            //         if (!PostExists(post.Id))
            //         {
            //             return NotFound();
            //         }
            //         else
            //         {
            //             throw;
            //         }
            //     }

            //     return RedirectToAction(nameof(Index));
            // }
            // ViewBag.Categoryid = GenerateList();
            // return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var post = await _context.Posts.FindAsync(id);
            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(Guid id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
    }



}

Areas/Author/Views/Posts/Create.cshtml
@model personalblog.Models.ViewModels.PostVM

@{
    ViewData["Title"] = "Create a Post";
    
}

<!-- Page Header -->
  <header class="masthead" style="background-image: url('../img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>@ViewData["Title"]</h1>
            <a asp-route-area="Author" asp-controller="Posts" asp-action="Index" class="btn btn-secondary">Back to List</a>
            <!-- <span class="subheading">A Blog Theme by Start Bootstrap</span> -->
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-md-12">
        <form asp-route-area="Author" asp-controller="Posts" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                      <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" placeholder="Title" />
                <p class="help-block text-danger">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </p>
            </div>
            
            <div class="form-group floating-label-form-group controls">
                <label asp-for="Categoryid" class="control-label"></label>
                <select asp-for="Categoryid" asp-items="ViewBag.Categoryid" class="form-control"></select>
                <p class="help-block text-danger">
                    <span asp-validation-for="Categoryid" class="text-danger"></span>
                </p>
            </div>

          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label asp-for="Subtitle" class="control-label"></label>
                <input asp-for="Subtitle" class="form-control" placeholder="Subtitle" />
                <p class="help-block text-danger">
                    <span asp-validation-for="Subtitle" class="text-danger"></span>
                </p>
                
            </div>

          </div>
            
           <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label asp-for="Body" class="control-label"></label>
                <!-- <input asp-for="Body" class="form-control" placeholder="Body" /> -->
                <textarea asp-for="Body" class="form-control" placeholder="Body" >                  
                
                </textarea>
                <p class="help-block text-danger">
                    <span asp-validation-for="Body" class="text-danger"></span>
                </p>
                
               
                
            </div>

          </div>
             <div class="form-group ">
                <input asp-route-area="Author" asp-controller="Posts" type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
  </div>

  </div>

</div>



  <script src="~/lib/tinymce/tinymce.min.js"></script>
  <script>
    tinymce.init({
    selector: '#Body',
    height: 400,
    theme: 'silver',
    menubar: false
    });
  </script>

Areas/Author/Views/Posts/Delete.cshtml
@model personalblog.Models.Post


<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
@section Scripts{
    <script>
    $(document).ready(function(){

        $(".btn-danger").click(function(e){
            var link =$(e.target);
           
          if(confirm("Do you want to delet this post?")){
              $.ajax({
                    url:"Areas/Author/Views/Posts/" + link.attr("value"),
                    method:"Delete"
                })
                .done(function(){
                    link.parents("form").fadeOut(function(){
                        $(this)
                        .remove();})

                })
                
       

          }  
         

           
      
            
        });
            
    });
    </script>  
}
        
            
            
      


     
    
            
      
  

 
 



             

Areas/Author/Views/Posts/Details.cshtml
@model personalblog.Models.ViewModels.PostCommentVM

<!-- Page Header -->
  <header class="masthead" style='background-image: url(@Url.Content("~/img/post-bg.jpg"))'>
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>@Html.DisplayTextFor(m=>m.Post.Title)</h1>
            <h2 class="subheading">@Model.Post.Subtitle</h2>
            <span class="meta">Posted by
              <a href="#">@Model.Post.Author.UserName</a>
              on @(String.Format("{0: MMMM dd yyyy}", Model.Post.CreatedAt))
              </span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
 
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          @Html.Raw(Model.Post.Body)
        </div>        
      </div>
    </div>
  </article>
 
  <section  class="mb-5">
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
<form asp-route-area="Author" asp-controller="Posts" asp-action="details" >
  <input  type="hidden" asp-for="PostId" />
      <div class="form-group row">
                <label asp-controller="Posts" asp-for="CommentText" class="col-md-2 control-label-comment"></label> 
                <div class="col">
                <textarea asp-controller="Posts" asp-for="CommentText" class="form-control" >
                </textarea>
                <span asp-validation-for="CommentText" class="text-danger"></span>
                </div>
      </div>
             <div class="form-group">
               <div class="col-md-2"></div>
               <div class="col">
                <input   type="submit" value="Add" class="btn btn-primary" />
               </div>
            </div>
            </form>
      </div>
      
    </div>
     </div>
  </div>
  </section>

  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
           
       <ul class="list-unstyled">
         @foreach (var item in Model.Post.Comment) {
  <li class="media mb-5">
    <img src="~/img/post-sample-image.jpg" class="img-thumbnail mr-3" alt="..." width="200px">
    <div class="media-body">       
      @item.CommentText
    </div>
  </li>
         }
  </ul>
  </div>
    
      </div>
    </div>
  </section>
  

<div class="container">
    <div class="row">
        
    </div>
    <a asp-action="Edit" asp-route-id="@Model.Post.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Author/Views/Posts/Edit.cshtml
@model personalblog.Models.ViewModels.PostVM



<h4>Edit Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-route-area="Author" asp-controller="Posts" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subtitle" class="control-label"></label>
                <input asp-for="Subtitle" class="form-control" />
                <span asp-validation-for="Subtitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>                
                <textarea asp-for="Body" class="form-control" ></textarea>
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">               
                <label asp-for="Category" class="control-label"></label>                                                                 
               <select asp-for="Categoryid" asp-items="ViewBag.Categoryid" class="form-control"></select>
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            
                    
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    <script src="~/lib/tinymce/tinymce.min.js"></script>

    <script>
         tinymce.init({
    selector: '#Body',
    height: 400,
    theme: 'silver',
    menubar: false
    });
    </script>
}

Areas/Author/Views/Posts/Index.cshtml
@model IEnumerable<personalblog.Models.Post>
   

    @{
    ViewData["Title"] = "Posts";
    
}

<!-- Page Header -->
  <header class="masthead" style="background-image: url('../img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>@ViewData["Title"]</h1>          
            <a  asp-route-area="Author" asp-controller="Posts" asp-action="Create" class="btn btn-success">Create Post</a>
            <!-- <span class="subheading">A Blog Theme by Start Bootstrap</span> -->
          </div>
        </div>
      </div>
    </div>
  </header>

<div class="container">
   <div class="row">
       <div class="col-lg-12 col-md-12 mx-auto">
</div>
</div>
</div>           

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subtitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoryid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subtitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoryid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th></th>
        </tr>
    </tfoot>
    <tbody>
@foreach (var  item in Model) 
{
        <tr>
            <td>
                @{
                var status = "Drafted";
                    if(item.Status==(byte)personalblog.Models.PostStatus.Published){
                        status = "Published";
                    }
                    else if (item.Status==(byte)personalblog.Models.PostStatus.Unpublished){
                        status ="Unpublished";
                    }
                }
                @status
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subtitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Categoryname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                <a  asp-action="Edit" asp-route-id="@item.Id">
                     <span class="edit">
                        Edit
                    </span>            
                  </a>   
                         |
                <a   asp-action="Details" asp-route-id="@item.Id">
                  <span class="details">
                        Details
                    </span>
                </a>   
                             |
                <a  asp-action="Delete" asp-route-id="@item.Id">
                  <span class="delete">
                         Delete
                    </span>
                </a>

                @if(item.Status==(byte)personalblog.Models.PostStatus.Draft 
                || item.Status==(byte)personalblog.Models.PostStatus.Unpublished){
                       <form  asp-action="Publish" asp-route-id="@item.Id">
                  <button class="btn btn-primary  "> 
                  <span class="publish">
                    Publish
                    </span>
                      
                  </button>
                </form>
                }
                else {
                    <form  asp-action="Unpublish" asp-route-id="@item.Id">
                  <button type="button" class="btn btn-warning"> 
                  <span class="unpublish">
                   Unpublish
                    </span>
                      
                  </button>
                  
                </form>
                }
            </td>
        </tr>
}
    </tbody>
</table>
       </div>
   </div>
</div>